on: push
name: Test Workflow
jobs:
  installDependencies:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        uses: actions/npm@master
        with:
          args: install
      - name: Test Code
        uses: actions/npm@master
        with:
          args: test
